@extends('layouts.main')

@section('title', 'Home')

@section('content')
    <div class="banner flex relative">
        <div><img src="{{URL('/images/cake1.jpg')}}" alt="Cake"></div>
        <div><img src="{{URL('/images/cake2.jpg')}}" alt="Cake"></div>
        <div><img src="{{URL('/images/cake3.jpg')}}" alt="Cake"></div>
        <div class="banner-text absolute"></div>
    </div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nulla laboriosam ea deleniti illum amet odit cumque aliquid consectetur ratione temporibus quo tempore voluptatibus a, in adipisci minima. Natus ea laudantium fugiat, veritatis totam praesentium error voluptate soluta hic nobis? Eligendi fugiat nulla et placeat reiciendis sed culpa vitae asperiores amet aspernatur quaerat incidunt maxime quasi dolorem dolores eos illum dolor repellendus earum, repudiandae quia totam laboriosam id cupiditate? Est sapiente placeat totam cupiditate iusto! Alias sit minima odit neque itaque quasi velit repudiandae, ipsum eligendi explicabo aspernatur quis rerum illo, quia nam consequuntur nulla magni in ducimus repellendus! Placeat possimus consequuntur, quas nobis cum iste aut porro excepturi neque, ut minus impedit quasi ipsam exercitationem non quo velit ullam. Vero ex incidunt atque pariatur ea totam vitae maxime reprehenderit molestias! Assumenda, impedit! Impedit itaque nam, quia dolores perferendis atque quos quas? Omnis repudiandae quidem ratione, quo voluptates numquam, ab exercitationem harum consequatur labore quisquam repellendus at nisi? Ipsa sequi provident voluptatem neque, earum vel? Quos deserunt reiciendis asperiores illo, quo sit laborum, quam cumque reprehenderit, labore aliquam! Expedita, repellendus exercitationem odio nulla ab enim dolores nemo possimus quisquam? Dolore, architecto deserunt asperiores harum accusantium sapiente, ut facilis id dicta ratione laborum, voluptatibus consequuntur a rerum inventore dolor ducimus! Iste, adipisci pariatur magnam fugiat, esse modi enim nam aperiam eius, dolore placeat nisi dolores. Adipisci quae voluptates dolorum eligendi explicabo vitae nisi quas optio, excepturi iure labore et laboriosam aut voluptas dignissimos alias, rem consequatur nam unde, suscipit impedit? Similique illum odit tenetur veniam facilis exercitationem recusandae consequuntur perferendis iure aspernatur libero velit, doloribus repellat nesciunt est non dolorum amet adipisci impedit ea beatae ex? Perferendis dolorum dolores, facilis odio repellendus cumque eligendi obcaecati explicabo ad! Placeat ipsa inventore, quidem, alias ut facere recusandae qui a temporibus harum repellendus veritatis enim nostrum nihil laboriosam, illo beatae blanditiis! Nam, libero, hic in odit fugit fuga possimus ad soluta maxime architecto nihil error! Dolor iste officia adipisci suscipit commodi, aliquid at possimus corrupti repellendus voluptatibus itaque velit placeat vero illo ipsam enim ipsum consequuntur laborum incidunt impedit accusantium eligendi. Qui repellat ex ab fuga eius ratione omnis consequatur ducimus nemo. Numquam consectetur tenetur aperiam eligendi optio accusamus ab quo! Vero culpa labore neque est, sed amet suscipit consectetur eaque at ex expedita, et quibusdam tempora nesciunt a consequatur cupiditate dolorem. Repellendus eos quae quisquam magnam neque quibusdam tenetur earum illum assumenda pariatur!</div>
@endsection